.circleci/config.yml, README.md, context.go, context_test.go, help_test.go, kong.go, kong_test.go, mapper.go, mapper_test.go, model.go, options.go, resolver.go, resolver_test.go, scanner.go, tag.go, tag_test.go
Resolvers are used to provide values for flags from external sources such as
environment variables or configuration files. Resolvers are included for JSON
configuration files and environment variables.
=> Implement flag "resolvers".

build.go
Or is it not supposed to be passed?
=> fix: `hidden` tag is not passed to the flag object

README.md
This is just a single word update to make the hook sample code in README.md compilable.
=> Fix hook sample in README.md.

README.md, mapper.go, mapper_test.go, tag.go
=> add support to make map separator configurable

help.go
Fixes #38 :-)
And also some people are bothered by the fact that the help function terminates with exit code 1: [reddit](https://www.reddit.com/r/golang/comments/f454o4/best_practices_or_tips_writing_a_cli_tool_with/fhyo8t5?utm_source=share&utm_medium=web2x)
=> change help exit code to 0

help.go
=> make HelperOptions CommandTree method exported

options.go
`PostBuild` should be a global options instead of being a method of `*kong.Kong`.
=> Make `PostBuild` global.

README.md, build.go, context.go, model.go, tag.go, tag_test.go
This forks and fixes the CI for the original PR opened at https://github.com/alecthomas/kong/pull/95
Closes #66
=> Add support for command aliases

resolver.go, resolver_test.go
Added support of sub objects to JSON resolver.
=> Added sub objects support in JSON resolver

help_test.go, model.go
Add aliases to all help output instead of tree only
=> Add aliases to ALL help output

README.md
Per suggestion in https://github.com/alecthomas/kong/issues/88#issuecomment-869744627.
=> [#88] Use reflect-compatible struct tags in examples

_examples/docker/main.go, _examples/server/console.go, _examples/server/main.go
=> Use reflect-compatible struct tags in examples and make linter happy

model.go, model_test.go, tag.go
=> Fix that default should not override the placeholder

build.go, help.go, interpolate.go, interpolate_test.go, kong.go, kong_test.go, model.go
=> Do not add environment variable to help it is already present

util.go, util_test.go
It allows one to do have something like `git -C` does.
=> Add ChangeDirFlag to allow changing the current working directory

README.md, build.go, context.go, kong_test.go, model.go, tag.go
=> Cmd can be passthrough now, too

context.go
This commit solves issue alecthomas/kong#264
I've checked this code with my service, the panics are gone.
=> fix: Change the application flags order avoiding panics

mapper_linux_test.go
=> fix linux build

help.go
=> fix for counter type rendering as INT

mapper_windows_test.go
Follow up to #394, specifically [this comment][1].
[1]: https://github.com/alecthomas/kong/pull/394#discussion_r1421683093
=> mapper_windows_test: assert.NotZero for nil check

README.md
Fixes: https://github.com/alecthomas/kong/issues/473
Fixes: https://github.com/alecthomas/kong/issues/487
=> Document about binds with example

mapper.go, mapper_test.go
=> Support parsing integer literals

README.md
=> fix: broken internal link

levenshtein.go
Resolve https://github.com/alecthomas/kong/issues/537 per https://github.com/alecthomas/kong/issues/537#issuecomment-2978998135
=> Update the license of the levenshtein method
