alecthomas/kong

help.go, help_test.go
Following up #29 and #30, I noticed that the default help looks quite duplicative since only the help text of the last command in chain is viewed. I needed an option to also show the help text of the command nodes in an appropriate way.  This is what I came up with.
It introduces an additional help option that overrides the others. Then it prints a tree view of the nodes, their sub commands, and arguments. It looks like that in the output:
```bash
Command Tree:
version                     display the app version
help                        show help for a command
|- [<command> ...]          the commands for which to show help
build                       build Docker tags from the given tag vectors
|- from                     determine the source of the tag vectors
|  |- stdin …
```
=> feat: add a command tree help view

README.md, build.go, context.go, kong_test.go, model.go, tag.go
Prevents more than one flag from being used at once within an xor group:
```
var cli struct {
One   bool   `xor:"group"`
Two   string `xor:"group"`
}
```
=> XOR groups for flags.

README.md
More than once I've had to dig into the code to work out how the keys are formatted in the JSON resolver. This will hopefully save some time for others!
=> A note in the README linking to a JSON example.

help.go
This quick change seems to fix the issue #38 by returning `0` for the exit code when calling `--help` 
Let me know if I'm overlooking some other use case with this code block that requires another approach to resolving this.  😃
=> Initial --help returns exit code 0 change

README.md, help.go, help_test.go, interpolate.go, kong.go, kong_test.go, options.go
As discussed in #60 I made the following changes: 
- add `HelpValueFormatter` (with test)
- remove env interpolation
=> add HelpValueFormatter as discussed in #60

benchmark_test.go, interpolate.go, interpolate_test.go, kong.go, options.go
I ran across an issue where having a large number of variables to interpolate can significantly slow down `kong.New()`.  In my case I had around 5,000 variables and it took about five seconds to run my program with `--help`.
The problem is in `kong.interpolate()`. Because it calls `Vars.CloneWith()` for each field, its complexity is roughly O(n<sup>2</sup>).
This PR updates `kong.interpolateValue()` so that `Vars.CloneWith()` is not called in most cases. It will only be called if `value.Tag.Vars` is populated or if interpolation modified value.Enum of value.Default.
It also updates `Vars.CloneWith()` to preallocate the output map.
I added benchmarks to show the performance improvement.  I'm happy for them to be removed before merging if you don't want to keep them around. Their primary …
=> fix performance issue in interpolation

kong.go
Tested on my machine - the little tweak works for both the global --help summary and sub-command summary as well. `-h` is now the default short-hand for `--help`.
=> Added -h as default short parameter for the automatic --help flag.

help_test.go
Commit c77deac080b5dd847a46540a186ea923b68b276a in PR #83 added `h` as the short flag for help, but the help tests were not updated. Update the tests with the `-h` in the help output.
=> Fix help tests with the introduction of -h

mapper.go, mapper_test.go, model.go, model_test.go, tag.go
According to the README.md, a value of `"none"` for the `sep` tag (for
slices) and `mapsep` (for maps) is meant to disable the separator that
would allow multiple entries to be added from a single argument.
However, using `"none"` just set the separator to the rune `'n'`.
Fix the parsing of the tag, and also update `SplitEscaped` to not split
with a separator of `-1`.
Add a new test for the new cases.
=> Fix sep:"none" and mapsep:"none"

context.go, kong.go, options.go
Adds a UsageOnMissing option which configures Kong to omit errors and
display usage when a command is invalid due to a missing argument. This
can be useful if a user wishes for the top-level command print usage
when no args are supplied, or if they would prefer child commands which
have their own subcommands to print usage specific to that command.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
I have provided some examples below when used with `crank` the CLI for @crossplane. Note that they all also have `UsageOnError()` supplied. This demonstrates how `UsageOnMissing()` plays nicely (i.e. no duplicate usage msg) by not returning an error.
**Top-level command without UsageOnMissing()**
```
$ crank
Usage: crank <command>
A tool for building platforms on Crossplane.
Flags:
-h, …
```
=> Add UsageOnMissing option to Kong

context.go, error.go, kong.go
Refactors usageOnMissing option to not run parent commands after
printing usage when a child node is missing.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
Follow up to #108 
@alecthomas I opted to not make the custom error type (and related functions) exported because I don't see it as worth adding to the public API.
=> Do not run parent node on missing child err with usageOnMissing option

context.go
`PrintUsage()` returns now the error from the `c.help()` call
Fix #116
=> Fix return err for PrintUsage

README.md, build.go, help.go, help_test.go, kong.go, model.go, options.go
Fix #134
@alecthomas It is still lacking support for grouped flags, I wanted to check with you that this PR is welcome and on the right path first.
Here's what's implemented so far:
* Ungrouped commands are displayed first, under a "Command:" group.
* Each group is printed in order of appearance.
* Tree mode ignores group for now.
* This part is not so easy to implement, maybe that's a reasonable limitation.
I think it could be useful to add some group metadata as well. In this case, the `group` tag would be a key referencing a declared Group metadata. We could store:
* The group title, in case it's long and to be able to modify it in only one spot.
* Git headings are quite long, e.g. `start a working area (see also: git help tutorial)`
* A short help message displayed under the group …
=> Add support for groups in the default HelpPrinter

help.go, help_test.go
When FlagsLast is set to true, flags are printed after commands.
- Added HelpOptions.FlagsLast bool
- Added test TestFlagsLast
=> Help Option to position flags in help output

help.go, help_test.go
Couldn't find a good example of how other tools format their command aliases, so just went with putting them in parens:
```
Usage: test-app <command>
A test app.
Flags:
-h, --help    Show context-sensitive help.
Commands:
one (un,uno)         subcommand one
- thing              subcommand thing
- <arg>            argument
- <other>            subcommand other
two                  Another subcommand.
- <three>            Sub-sub-arg.
- four (for,fore)    Sub-sub-command.
Run "test-app <command> --help" for more information on a command.
```
=> Add aliases to tree help output

help.go, help_test.go, kong.go, options.go
Add `kong.ShortUsageOnError()` option similar to `kong.UsageOnError()`.
For a custom short usage message use `kong.ShortHelp(kong.HelpPrinter)`
Add tests for UsageOnError and ShortUsageOnError.
=> options: Add kong.ShortUsageOnError() option

README.md, context.go, help.go, help_test.go, kong_test.go, model.go, tag.go
Adds support for a new `negatable` struct tag, which will automatically set a boolean Struct flag value to `false` if the flag's name starts with `--no-`, even when the default is `true`. This idea is shamelessly stolen from the [`commander` npm library](https://github.com/tj/commander.js#other-option-types-negatable-boolean-and-booleanvalue)
For example:
```go
type Cmd struct {
Sort bool `default:"true",negatable`
}
```
Calling
```sh
command
command --sort
```
Will set `Sort` to `true`, but
```sh 
command --no-sort
```
Will set `Sort` to `false`.
It avoids the situation of having to do:
```go
type Cmd struct {
NoSort bool
}
func (c *Cmd) Run() error {
if !c.NoSort {
// Double negations are hard to read!
}
return nil
}
```
=> Add support for negatable boolean flags

README.md, mapper.go, mapper_test.go
I passed `-` into a path flag, expecting to be able to special-case it to stdout in my command. Unfortunately it was expanded to an absolute file path and so my command wrote a file called `-` in the current working directory instead.
This can obviously be achieved with a custom mapper, but do you think it would it make sense to allow `-` in the path mapper by default?
=> Allow `-` for stdout in path mapper

help.go, help_test.go
With a CLI that has lots of options, subcommands are useful for making the toplevel help message less cluttered. This makes it even less so.
Without option:
```
Commands:
cmd               Some command
has-subs sub-1    Subcommand 1
has-subs sub-2    Subcommand 2
```
With option:
```
Commands:
cmd         Some command
has-subs    Command with subs
```
=> Add option to not expand subcommand help

mapper.go
I was reading through the source when I found what looked like a small copy-paste error.  Here's a trivial patch.  Thank you for these libraries, Alec.
`UnmarshalBinary` did seem to work OK on my first test.  It wasn't until I read the source more carefully that I realised the field must be a _pointer_ to a type that implements `UnmarshalBinary` in order to trigger a panic:
```go
package main
import (
"errors"
"github.com/alecthomas/kong"
)
type SomeTextFlag struct{}
func (f *SomeTextFlag) UnmarshalText(text []byte) error {
return errors.New("hello from UnmarshalText")
}
type SomeBinaryFlag struct{}
func (f *SomeBinaryFlag) UnmarshalBinary(data []byte) error {
return errors.New("hello from UnmarshalBinary")
}
var cli struct {
Text   *SomeTextFlag
Binary *SomeBinaryFlag
}
func main() { …
```
=> mapper: correct text/binary typo (panic)

README.md, build.go, context.go, mapper_test.go, model.go, tag.go
This new tag tells the parser to stop processing flags after the
positional argument is encountered.
This is particularly useful for subcommands that forward their arguments
to an external program, and makes it possible to implement commands
like `kubectl exec` or `docker run`.
=> tag: add passthrough for positional arguments

options.go
Without this fix you get the following panic when a resolver's file is not readable:
```console
command --help
panic: ~/.config/command/config.yaml: open /home/user/.config/command/config.yaml: permission denied
goroutine 1 [running]:
github.com/alecthomas/kong.Parse(0xacf6c0, 0xc0000b8900, 0xc0000b0300, 0x8, 0x8, 0x22)
/home/rz/golang/pkg/mod/github.com/alecthomas/kong@v0.2.16/global.go:11 +0x145
main.main()
```
The easiest way for read permission is via `os.Open`
=> fix panic resolver's configuration file does not have read permission

help.go, mapper.go, mapper_test.go, model.go
Fixes #125 
This allows things like having the placeholder text be `--config=/path/to/file or "-"` or listing enumerations like `--level=trace|debug|info|warn`, dates like `--start-time="2000-11-01 23:00:00"` etc.  None of these are implemented out of the box - this is only for new custom mappers.
To use this implement the `PlaceHolderProvider` interface along with `MapperValue`.  Implementing that interface is optional, the default placeholder will be used otherwise.
=> Fixes #125: Support custom per-mapper placeholder text

context.go, kong_test.go
Fixes https://github.com/alecthomas/kong/issues/170
The logic of negating boolean flag value was added inside [Context.Apply()](https://github.com/alecthomas/kong/blob/master/context.go#L640) method, which is executed both for `Parse` and `Run` calls. This led to the negated flag value being parsed properly, but being negated again during the call to `Run`.
=> Fix issue with negatable flag being negated twice

options.go, resolver_test.go
Generating environment variable names for flags.
```go
type Some {
Value string
}
cli := struct {
Some  Some `prefix:"some." embed:""`
}
kong.Parse(root, kong.Env("PREFIX"))
```
Generates:
``    --some.value -> PREFIX_SOME_VALUE
``
=> Environment option

.golangci.yml, README.md, build.go, context.go, kong_test.go, model.go
Allow default commands to have sub-commands, args and flags when tagged 
with `default:"withargs"`. This makes specifying the name of the command
on the CLI completely optional as long as the args to that command are not
ambiguous with other commands.
Re-work the validation of the CLI grammar so that the constraints on default
commands are checked during `build()` and not `trace()` - this seems to be
more correct and where other parts of the grammar are validated. Also add
some missing validation for default commands with positional args - only
branching args were disallowed, but the error message seemed to imply that
all args should be disallowed.
=> Allow default commands with cmds/args/flags

build.go, context.go, global_test.go, guesswidth_unix.go, kong.go, model.go, tag.go
The panic, catch and re-panic pattern leads to ugly reported stack-traces for real panics (not panics which are actually kong errors). As in kong's catch is the last entry, where usually it immediately shows the culprit there. So I replaced that with bubbling the error up.
=> Bubble errors instead of panicking

build.go, kong.go, kong_test.go, options.go
@alecthomas this adds functionality to allow kong to ignore fields that match a certain pattern.
I needed this in order to be able to ensure that kong does not parse fields like `XXX_` that are automatically generated via protoc.
The regexp is kind of a big hammer but since this is for CLI generation, I figure the perf hit is OK. LMK.
=> Add ability to ignore fields that match given regex pattern(s)

callbacks.go, context.go, options.go
- factoring out other `Bind*` calls to delegate to `bindings`
=> Adds Context.BindToProvider

build.go, help_test.go
Before this change the EnvPrefix was applied to fields without env
specified, which resulted in strange and confusing help output.
=> Only prepend EnvPrefix if .Env is not empty.

kong.go, kong_test.go
Fixes issue #233 by enabling support for variable interpolation into the `env` struct tag.
```go
type cli struct {
EnvFlag string `env:"${myEnv}" help:"Looks at ${myEnv}"`
}
ctx := kong.Parse(&cli{}, kong.Vars{
"myEnv": "AN_ENV_VAR",
})
```
=> feat: add support for variable interpolation into env tag key

kong.go, resolver_test.go
Support was added for variable interpolation of the `env` tag in #234, but it did not fully succeed in practice. This PR ensures that the `Env` attribute is updated on both the `value.Flag` and `value.Tag` of the node being interpolated.
Without this change, when `context.Reset` is called, the `env` value on the tag is still something like `${envToBeInterpolated}`, even though the the flag's `env` might be `SOME_ENV_VAR`.
=> Fix env var interpolation

callbacks.go, options_test.go
It should not matter what exactly is the return type, only that `return out[0].Interface().(error)` succeeds, no?
=> Allow more flexible callback return error type

README.md
See: https://github.com/alecthomas/kong/issues/256
I made this addition to documentation to make it clearer. I think it is a pretty common use case and it makes it nice to immediatelly see how Kong does it. Because when initially reading README I was like "nice, they use structs for sub-commands, but, hm, what if you just want a struct".
=> Document nested data structure

README.md
Fixed the line number for json example in test.
=> fix: correct line number for json example

context.go, kong_test.go
Adds a check for if the xorGroupSet has been satisfied before building the list of missing flags.  Includes the test described in https://github.com/alecthomas/kong/issues/258.
=> fix required/xor behavior w/ > 2 flags

README.md
Removes + characters that were included from a previous diff.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
> Per usual, thanks for the time and effort put into this library!
=> Remove extraneous + in README.md

README.md, help.go, kong.go, kong_test.go
Help fails sometimes due to `kong.Parse()` calling `context.go:Context.Reset()` early in the function; this call to `Context.Reset()` makes subsequent calls to `model.go:Value.Reset()`; `Value.Reset()` calls `Parse` for environment variables and default values; `Parse` in turn calls `Value.Mapper.Decode()`, which executes the resolver; if the resolver fails, then `Parse` fails during `Reset`; originally, `--help` was implemented as a `BeforeApply` hook, but due to the above described call order, it wasn't getting called in some failure conditions; if `Reset` is moved to a later stage in `kong.Parse`, the hook can be called, allowing for usage to be printed.
Initially opening as a draft, as there may be unintended consequences of moving `Reset` around in `Parse` and changing `--help` to a …
=> fix: always help

mapper.go, mapper_linux_test.go, mapper_test.go, mapper_windows_test.go, util_test.go
Fixes #198
This change is needed to support the Windows path separator character, and use of `\<somechar>` sequences in general where `<somechar>` isn't the separator.
=> treat \ as escape only before a separator

mapper.go, mapper_test.go
Updated existing-file/dir mappers to early return if already set successfully, such that the default value is not checked if a user-provided value has already been verified successfully.  This is intended to avoid failures when a default value does not exist and the user-provided value does, allowing for successful continuation.
Added tests for existing-file/dir mappers.
Intended to fix https://github.com/alecthomas/kong/issues/26
=> fix: existing file/dir always checks default

go.mod, go.sum
gopkg.in/yaml.v3 has a vulnerability CVE-2022-28948 which is fixed in 3.0.1. This patch is a bump of the import version and a mod tidy.
=> Update yaml v3 to v3.0.1 to fix CVE 2022 28948 

kong_test.go, mapper.go
=> helpful error message when flag is missing values

build.go, kong_test.go
Closes #300 
Adds supports for validating if command names are not duplicated within a single node's children.
Panics if they are duplicated.
This is a breaking change in case a project has duplicated command names.
Positional arguments are not affected and can have duplicated names.
=> Panic on duplicate command names

context.go, mapper.go, mapper_test.go, model.go
`Active` struct member added to `Node`s and `Value`s to denote that the component in the grammar has been "activated" by CLI args.  During tracing, `Node`s and `Value`s are "activated", primarily to provide extra context to mapper functions.  `ExistingFileMapper` and `ExistingDirMapper` functions updated to validate paths only if their `Value`s are a part of the "active" branch in the CLI context.
=> Add Active member to Nodes and Values

kong_test.go, util.go
Similar to how `--help` was updated in https://github.com/alecthomas/kong/pull/298, `--version` changed to a BeforeReset hook so that it will always work.
=> fix: change VersionFlag to a BeforeReset hook

help_test.go, helpwrap1.18_test.go, helpwrap1.19_test.go
Closes #325
Addresses change in text wrapping since go1.19
=> go1.19 specific tests for text wrapping

README.md
With the #24, `Mapper` interface was changed. 
This PR changes the README.md to match the current state of `Mapper`.
=> Fix Readme mention about `Mapper` interface

build.go, kong_test.go
Closes #276
No other arguments can be after a cumulative argument.
This excludes required positional arguments such as `cmd <arg> ... <last>`.
I believe the best practice shall be - cumulative arguments are always last.
Let me know if you think required arguments shall be supported after cumulative. I'll be happy to update the PR.
=> Cumulative argument needs to be last

README.md, context.go, kong_test.go, mapper.go, tag.go
Merging #280 with master for this PR.
=> Merging issue 280 with master changes

mapper.go, mapper_test.go
`%v` uses E notation to format floats with more than 6 digits. Since JSON numbers are always floats, Kong breaks when loading large integers from JSON files.
=> Fix loading large integers from JSON files

mapper.go, mapper_test.go
I noticed that after merging [the fix for large numbers (#334)](https://github.com/alecthomas/kong/pull/334), the build was broken on the `master` branch [due to a linter complaint](https://github.com/alecthomas/kong/actions/runs/3101957356/jobs/5023801376).
Problem is that the `uintDecoder` is no longer a code duplication of `intDecoder`, because the adjustments by #334 only changed `intDecoder`. It’s not the linter directive that’s obsolete, but I rather think that `uintDecoder` must have that fix as well, because it suffers from the same problem.
In addition to the actual fix, I slightly adjusted the tests:
- I converted the Github link to an inlined explanation, just for convenience.
- Both cases for `int` and `uint` are now covered. I think it makes sense to have them together in one …
=> Fix large number decoding for unsigned types in JSON

build.go, callbacks.go, context.go, kong.go, options.go, options_test.go, tag.go
The former allows arbitrary structs to be embedded in the root of the CLI, with optional tags.
The latter allows an arbitrary function to be called using Kong's binding functionality.
=> feat: Embed() option and Context.Call()

kong_test.go, tag.go, tag_test.go
So far bare tags did not get unquoted, causing several problems. E.g., using backslashs in tags doesn't work as expected (I noticed when having a `default` tag containing a RegExp).
This also led to the issue described in #324. 
The PR related to that issue (#330) is not really tackling the problem, it's just trying to fix the most obvious symptoms.
I added a test to ensure things are working.
=> fix: handle contents of tags properly by unquoting them when necessary

context.go, kong_test.go
Fixes #332.
So there is no need to prepend the app name at this point because `kong.Errorf` prepends all outputs with app name already. So the app-level failures should just return the error. Only when it is deeper we need additional information about the node where the error is coming from.
=> fix: remove showing app name twice in errors

callbacks.go, context.go, kong.go, kong_test.go, options_test.go
Resolves https://github.com/alecthomas/kong/issues/383.
With this PR, kong will pass through error messages from commands’ `Run()` methods as is, without wrapping them up or reformatting them.
The `callMethod` is obsolete now, its only purpose was the error wrapping. The callers can use `callFunction` directly.
=> Drop automatic message prefix from command errors

.golangci.yml, README.md, config_test.go, mapper.go, mapper_test.go, util_test.go
io/ioutil has been deprecated for a while.
Replace all uses of it with equivalent APIs.
=> Drop references to io/ioutil

.github/workflows/ci.yml
Per the [Go Release Policy][1], upstream supports
only the two most recent major releases of Go.
For example, with Go 1.21 available, only 1.21 and 1.20 are supported.
Many projects adopt a similar support policy
to strike a balance between new features and backwards support.
[1]: https://go.dev/doc/devel/release#policy
If Kong has the same policy,
it makes sense to test against both versions of Go.
This change adds a test matrix to CI,
testing against both Go 1.20 and 1.21,
on both Windows and Linux.
For Linux, it installs the desired version on demand,
because I couldn't find a way to have multiple versions
coexist with Hermit.
=> ci: Test against Go 1.20 and 1.21

mapper.go, mapper_test.go
I have a use case where I would like to differentiate between an unset path and an empty string path (which expands to the current directory).
This PR updates the `pathMapper` function to allow a `path` type to be applied to a `*string` to make this differentiation per the pointer behaviour described here: https://github.com/alecthomas/kong#pointers
=> Support string pointers for path mapper

build.go, kong_test.go
Make sure we remove all the aliases from the seenFlags tracker just like we do with other flags/short flags
=> Aliases can be duplicated between different sub commands

_examples/shell/help/main.go
=> Update help example to use vars

README.md
The README documentation for `kong.Help` refers to a non-existent function, which I think was previously renamed. This fixes it.
=> Fix reference to non-existent function in README

build.go, context.go, kong_test.go, options.go
This small MR allows using the func-to-interface trick to implement a command (see commandFunc in kong_test.go).
This is useful e.g. for commands that have no flags or arguments of their own, but instead receive all required information via bound  parameters.
:question: we could (but don't need to) also provide a `CommandFunc` type, analogous to `http.HandlerFunc`.
=> feat: allow non-structs to be used as commands

kong.go, kong_test.go
If there is trailing newline, `strings.Split` creates an empty last line in `lines`, making this function output an extra empty line at the end. Trimming trailing newlines fixes that.
=> Remove extra newline when message contains trailing newlines

context.go, kong_test.go
Given a grammar like this:
```golang
var cli struct {
Args []string `arg:"" optional:"" passthrough:""`
}
```
If Kong parses `cli foo -- bar`, it will populate `Args` with `[]string{"foo", "--", "bar"}` (including "`--`"). However, if Kong parses `cli -- foo bar`, will populate `Args` with `[]string{"foo", "bar"}` (leaving off `"--"`).
This differs from the behavior of a passthrough Command, where `"--"` is included with the args in both cases.
There are 3 places where `c.endParsing()` is called
1. When `node.Passthrough` is true: https://github.com/alecthomas/kong/blob/5f9c5cc822bdb888a3671c44d4688a6f602ecb90/context.go#L366-L368
2. When `arg.Passthrough` is true: https://github.com/alecthomas/kong/blob/5f9c5cc822bdb888a3671c44d4688a6f602ecb90/context.go#L451-L453
3. When `"--"` is …
=> fix!: Include `--` in passthrough args

README.md
Hi, maintainer-san 👋🏽
Thank you so much for developing such a great package!
I found a broken anchor link in the document and fixed it.
You can check it works the README in [this branch](https://github.com/ebi-yade/kong/tree/fix/update-readme).
=> Fix broken anchor link in README.md

context.go, kong_test.go
Fixes bug introduced in 2544d3f00855f6857cf121ce04608296b5858e4a.
That commit refactored control flow slightly and missed a case
where the selected node is an application node but it does not
have a Run method.
The fix was straightforward:
Treat the "if application node" code path as a possible way to fill
`node`, and check it again afterwards.
Resolves #483
=> fix(Context.Run): Don't panic on unselected root node

callbacks.go, kong_test.go
(I realize that I opened this without discussing the feature first,
so if you don't think this feature makes sense, feel free to close this PR.
I've tried to outline the reasoning below.)
---
Relates to 840220c (#90)
This change adds support for hooks to be called on fields
that are tagged with `embed:""`.
If a command has several subcommands,
many (but not all) of which need the same external resource,
this allows defining the flag-level inputs for that resource centrally,
allowing subcommands to declare their dependency on these resources
and use them in their `Run` in a highly composible manner.
For example, imagine:
```go
type githubClientProvider struct {
Token string `name:"github-token" env:"GITHUB_TOKEN"`
URL   string `name:"github-url" env:"GITHUB_URL"`
}
func (g …
```
=> Support hooks on `embed:""` fields

callbacks.go, kong_test.go
Follow up to #493 and 840220c
Kong currently supports hooks on embedded fields of a parsed node,
but only at the first level of embedding:
```
type mainCmd struct {
FooOptions
}
type FooOptions struct {
BarOptions
}
func (f *FooOptions) BeforeApply() error {
// this will be called
}
type BarOptions struct {
}
func (b *BarOptions) BeforeApply() error {
// this will not be called
}
```
This change adds support for hooks to be defined
on embedded fields of embedded fields so that the above
example would work as expected.
Per #493, the definition of "embedded" field is adjusted to mean:
- Any anonymous (Go-embedded) field that is exported
- Any non-anonymous field that is tagged with `embed:""`
*Testing*:
Includes a test case for embedding an anonymous field in an `embed:""`
and an `embed:""` …
=> hooks: Recursively search embedded fields for methods

kong.go, model.go, resolver.go
This is a draft as a discussion starting point. I need to add comments, and maybe simplify code a bit.
Closes: #477
=> Load environment variables as a resolver

build.go, kong_test.go
If a field in a struct is ignored with `kong:"-"`, any embedded fields
with the same name are also ignored. This allows an outer struct to
remove flags from an embedded struct by redefining it and adding a kong
ignore tag.
=> feat: Allow ignoring fields from embedded structs

context.go, kong_test.go, scanner.go
As Kong traces a sequence of command line arguments, it parses them and appends them to the parsed `Path` sequence. For each element in `Path`, these is a corresponding sequence of unparsed arguments. This change enables `Path` to yield these.
I have a package that uses Kong's hooks to instrument Kong applications (to monitor usage, reliability, etc of internal tools). I would like to instrument the commandline arguments as well.
This change would enable it to work roughly as follows:
```golang
func (Foo) BeforeApply(app *kong.Kong, ctx *kong.Context, t *Tracker) error {
command := []string{ctx.Model.Name}
var args []string
for _, path := range ctx.Path {
if path.Command != nil {
command = append(command, path.Command.Name)
args = path.Rest()
}
}
app.Exit = t.exit(app.Exit) …
```
=> feat: Allow kong.Path to describe remaining unparsed args

error.go, exit.go, help_test.go, kong.go
feat: Allow Kong to exit with semantic exit codes
At Block, we've instrumented a number of commandline tools and set SLOs on some tools' reliability. To do that effectively, we had to partition usage errors from reliability issues. We looked at [prior art](https://github.com/square/exit?tab=readme-ov-file#reserved-codes-and-prior-art) and, taking inspiration from HTTP, defined [a set of semantic exit codes](https://github.com/square/exit?tab=readme-ov-file#about) in ranges: 80-99 for user errors, 100-119 for system errors.
We've been wrapping errors in `exit.Error` at whatever level of the stack can tell which class an error is and unwrapping them at exit (`os.Exit(exit.FromError(err))`).
This adds support for semantic exit codes to Kong, to `FatalIfErrorf`, which is used internally by …
=> feat: Allow Kong to exit with semantic exit codes

README.md, kong.go, kong_test.go
Add support string interpolation in placeholder values.
Some tools like to place the supported enum values in the placeholder string. So, it's a tad annoying being able fill in the `enum` value from vars but not the `placeholder` value.
=> feat: Placeholder string interpolation.

README.md, hooks.go, kong.go, kong_test.go, options.go
Lets you pass `kong.WithBeforeApply` along with a function that supports dynamic bindings to register a `BeforeApply` hook without tying it directly to a node in the schema.
Also updates the README.md to [list a table of hooks with their meanings](https://github.com/boblail/kong/tree/lail/register-hooks-via-Options?tab=readme-ov-file#hooks-beforereset-beforeresolve-beforeapply-afterapply).
=> feat: Allow configuring hooks via Kong's functional options
